/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as docsSol from "./Docs.sol";
export type { docsSol };
export type { Counter } from "./Counter";
export type { DelegationRegistry } from "./DelegationRegistry";
