/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as docsSol from "./Docs.sol";
export { Counter__factory } from "./Counter__factory";
export { DelegationRegistry__factory } from "./DelegationRegistry__factory";
