/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  EssentialContext,
  EssentialContextInterface,
} from "../../../contracts/fwd/EssentialContext";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "trustedForwarder",
        type: "address",
      },
    ],
    name: "setTrustedForwarder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class EssentialContext__factory {
  static readonly abi = _abi;
  static createInterface(): EssentialContextInterface {
    return new utils.Interface(_abi) as EssentialContextInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EssentialContext {
    return new Contract(address, _abi, signerOrProvider) as EssentialContext;
  }
}
