[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/unit'
script = 'deploy'

cache_path  = 'forge-cache'

[rpc_endpoints]
goerli               = "${GOERLI_RPC_URL}"
mainnet              = "${MAINNET_RPC_URL}"

polygon-mumbai       = "${MUMBAI_RPC_URL}"
polygon-mainnet      = "${MATIC_RPC_URL}" 

arbitrum-goerli      = "${ARB_GOERLI_RPC_URL}" 
arbitrum-mainnet     = "${ARB_MAINNET_RPC_URL}" 
arbitrum-nova        = "${ARB_NOVA_RPC_URL}" 

avalanche-fuji       = "${AVAX_FUJI_RPC_URL}"
avalanche-mainnet    = "${AVAX_MAINNET_RPC_URL}"

optimism-mainnet     = "${OPT_MAINNET_RPC_URL}"
optimism-goerli      = "${OPT_GOERLI_RPC_URL}"

base-goerli          = "${BASE_GOERLI_RPC_URL}"

zora                 = "${ZORA_RPC_URL}"

[etherscan]
goerli           = { key = "${ETHERSCAN_API_KEY}" }
mainnet          = { key = "${ETHERSCAN_API_KEY}" }

polygon-mumbai   = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com" }
polygon-mainnet  = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com" }

arbitrum-goerli  = { key = "${ARBISCAN_API_KEY}", url = "https://api-goerli.arbiscan.io/api" }
arbitrum-mainnet = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
arbitrum-nova    = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
 
optimism-mainnet = { key = "${OPTIMISM_API_KEY}", url = "https://api-optimistic.etherscan.io" }
optimism-goerli  = { key = "${OPTIMISM_API_KEY}", url = "https://api-goerli-optimistic.etherscan.io" }

avalanche-mainnet = { key = "${AVAX_API_KEY}", url = "https://api.snowtrace.io" }
avalanche-fuji    = { key = "${AVAX_API_KEY}", url = "https://api-testnet.snowtrace.io"}