/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fwd from "./fwd";
export type { fwd };
import type * as test from "./test";
export type { test };
